import time
from pyautogui import *
time.sleep(2.5)
keyDown('u')
for i in range(7):
    time.sleep(.5)
    press('5')
    time.sleep(.5)
    press('6')
    time.sleep(.5)
    press('7')
time.sleep(.5)
time.sleep(.5)
for i in range(3):
    time.sleep(.5)
    press('4')
    time.sleep(.5)
    press('8')
time.sleep(.5)
press('8')
time.sleep(.5)
press('8')
time.sleep(.5)
press('1')
time.sleep(.5)
press('1')
time.sleep(.5)
press('2')
time.sleep(.5)
press('3')
keyUp('u')